### ISSUE TITLE
[feature request] add a docker images's repo address, such as harbor

### ISSUE THREAD

**Issue by Wercurial** [kubedl-io/kubedl#264]
**What would you like to be added**:
hi,I hope I can add an option to support custom kaniko generation model mirror push warehouse address, such as harbor.

**Why is this needed**:
In the cloud native environment, more and more companies choose to build docker image warehouses, such as harbor.

**Comment by Wercurial** [comment]
Oh, sorry. I think I found the correct usage. I need to specify the harbor's address in the imageRepo.
```
apiVersion: "training.kubedl.io/v1alpha1"
kind: "TFJob"
metadata:
  name: "distributed-tfjob"
  namespace: spark-k8s
spec:
  cleanPodPolicy: None
  # modelVersion defines the location where the model is stored.
  modelVersion:
    # The model name for the model version
    modelName: mymodel
    # The dockerhub repo to push the generated image
    imageRepo: 172.16.2.132:30002/toolbox/mymodel
    storage:
.....
```
